name: CI with Caching

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # First, check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up the cache
      - name: Cache npm dependencies
        id: cache-npm-deps
        uses: actions/cache@v4
        with:
          # The directory to cache: npm's cache directory
          path: ~/.npm
          # The key for this cache entry
          key: cache-05de9f9

      # This step echoes whether a cache was found
      - name: prime-cache-05de9f9
        run: |
          if [[ "${{ steps.cache-npm-deps.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies restored from cache."
          else
            echo "Cache miss! No cache found for key: cache-05de9f9"
          fi

      # Install dependencies. This step will be slow on a cache miss
      # and very fast on a cache hit.
      - name: Install Dependencies
        run: npm ci
